# Horizontal Pod Autoscaler (HPA) for Synapse Workers
# IMPORTANT: Only synchrotron and generic-worker support HPA
# Other workers (event-persister, federation-sender, etc.) require manual scaling
# See docs/SCALING-GUIDE.md section 2.5 for full explanation

---
# Synchrotron HPA
# Synchrotron handles /sync requests - the most common client operation
# Stateless workers that can scale automatically without configuration changes
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: synapse-synchrotron-hpa
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: synchrotron-hpa
    app.kubernetes.io/instance: main
    matrix.instance: main
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse-synchrotron
  # Minimum replicas for HA (always have at least 2)
  minReplicas: 2
  # Maximum replicas - adjust based on cluster capacity
  # Each synchrotron pod handles ~1000 concurrent connections
  # For 20K CCU: 20000 / 1000 = 20 replicas theoretical max
  maxReplicas: 16
  metrics:
    # Scale based on CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Target 70% CPU utilization
          # Synapse workers are CPU-bound due to Python GIL
          averageUtilization: 70
    # Optional: Scale based on memory if /sync caches grow
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    # Scale up quickly to handle traffic spikes
    scaleUp:
      # Wait 60 seconds after scaling before evaluating again
      stabilizationWindowSeconds: 60
      policies:
        # Add up to 4 pods at once
        - type: Pods
          value: 4
          periodSeconds: 60
        # Or increase by up to 100% in 60 seconds
        - type: Percent
          value: 100
          periodSeconds: 60
      # Use the policy that adds the MOST pods (scale up aggressively)
      selectPolicy: Max
    # Scale down slowly to avoid flapping
    scaleDown:
      # Wait 5 minutes before scaling down
      stabilizationWindowSeconds: 300
      policies:
        # Remove only 1 pod per period
        - type: Pods
          value: 1
          periodSeconds: 120
      # Use the policy that removes the LEAST pods (scale down conservatively)
      selectPolicy: Min

---
# Generic Worker HPA
# Generic workers handle client API requests (room list, messages, etc.)
# Stateless workers that can scale automatically without configuration changes
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: synapse-generic-worker-hpa
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: generic-worker-hpa
    app.kubernetes.io/instance: main
    matrix.instance: main
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse-generic-worker
  # Minimum replicas for HA
  minReplicas: 2
  # Maximum replicas - adjust based on cluster capacity
  # Generic workers typically need fewer replicas than synchrotron
  # API requests are less frequent than /sync long-polling
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Min
