# Media Repository Worker StatefulSet
# Handles media upload and download endpoints
# Endpoints: /_matrix/media/*, /_matrix/client/*/upload, /_matrix/client/*/download
#
# Scale: 2-8 replicas based on media traffic
# Media is stored in MinIO S3, not locally
# MUST be StatefulSet for predictable naming (referenced in media_instance_running_background_jobs)

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse-media-repository
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: media-repository
    app.kubernetes.io/instance: main
    matrix.instance: main
spec:
  serviceName: synapse-media-repository
  replicas: 2  # Scale based on media load: 2-8 replicas

  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
      app.kubernetes.io/component: media-repository

  updateStrategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/component: media-repository
        app.kubernetes.io/type: worker
        app.kubernetes.io/instance: main
        matrix.instance: main
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/_synapse/metrics"

    spec:
      securityContext:
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 991
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: media-repository
                topologyKey: kubernetes.io/hostname

      initContainers:
        - name: install-s3-provider
          image: matrixdotorg/synapse:v1.119.0
          command:
            - sh
            - -c
            - |
              # Install S3 storage provider module
              pip install --user synapse-s3-storage-provider==1.4.0

              # Copy installed module to shared volume
              cp -r /home/synapse/.local/lib/python*/site-packages/* /mnt/python-packages/ || true

              echo "S3 storage provider installed successfully"
          volumeMounts:
            - name: python-packages
              mountPath: /mnt/python-packages
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

        - name: generate-worker-config
          image: matrixdotorg/synapse:v1.119.0
          command:
            - sh
            - -c
            - |
              # Create worker-specific config
              cat > /config/worker.yaml <<EOF
              worker_app: synapse.app.generic_worker
              worker_name: media_repository_${HOSTNAME}

              # Replication
              worker_replication_host: synapse-main-0.synapse-main.matrix.svc.cluster.local
              worker_replication_http_port: 9093
              worker_replication_http_tls: false

              # Media workers handle media endpoints
              worker_listeners:
                - type: http
                  port: 8008
                  resources:
                    - names: [media]
                  x_forwarded: true

                - type: http
                  port: 9093
                  resources:
                    - names: [replication]

                - type: metrics
                  port: 9090
                  resources:
                    - names: [metrics]

              # CRITICAL: Enable media repo on this worker
              enable_media_repo: true

              # Worker log config
              worker_log_config: /config/log.yaml
              EOF

              # Process shared config
              envsubst < /config-template/homeserver.yaml > /config/homeserver.yaml
              cp /config-template/log.yaml /config/log.yaml
              cp /config-template/signing.key /config/signing.key
              chown -R 991:991 /config
              chmod 600 /config/signing.key

              echo "Media repository worker configured for ${HOSTNAME}"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matrix-postgresql-app
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: REDIS_PASSWORD
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: S3_SECRET_KEY
            - name: REPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: REPLICATION_SECRET
            - name: MACAROON_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: MACAROON_SECRET
            - name: REGISTRATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: REGISTRATION_SECRET
            - name: FORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: FORM_SECRET
            - name: TURN_SECRET
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: TURN_SECRET
            - name: KEY_VAULT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: synapse-secrets
                  key: KEY_VAULT_API_KEY
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
            - name: signing-key
              mountPath: /config-template/signing.key
              subPath: signing.key

      containers:
        - name: worker
          image: matrixdotorg/synapse:v1.119.0
          imagePullPolicy: IfNotPresent

          command:
            - python
            - -m
            - synapse.app.generic_worker
            - --config-path=/config/homeserver.yaml
            - --config-path=/config/worker.yaml

          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
            - name: replication
              containerPort: 9093
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP

          env:
            - name: SYNAPSE_WORKER
              value: "synapse.app.generic_worker"
            - name: SYNAPSE_WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            # Media cache (optional local cache before S3)
            - name: media-cache
              mountPath: /data/media_store
            - name: python-packages
              mountPath: /usr/local/lib/python3.11/site-packages
              readOnly: true

          # Media workers need more memory for thumbnailing
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          # Health probes
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2

          startupProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 991
            runAsGroup: 991
            capabilities:
              drop:
                - ALL

      volumes:
        - name: config-template
          configMap:
            name: synapse-config
        - name: config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: python-packages
          emptyDir: {}
        - name: media-cache
          emptyDir:
            sizeLimit: 10Gi  # Local cache before S3
        - name: signing-key
          secret:
            secretName: synapse-secrets
            items:
              - key: signing.key
                path: signing.key
                mode: 0600

---
# Headless service for media StatefulSet (required for pod DNS)
apiVersion: v1
kind: Service
metadata:
  name: synapse-media-repository
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: media-repository
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: media-repository
  ports:
    - name: http
      port: 8008
      targetPort: 8008
      protocol: TCP
    - name: replication
      port: 9093
      targetPort: 9093
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP

# NOTE: HPA is NOT used for media-repository because:
# - media_instance_running_background_jobs references synapse-media-repository-0 by name
# - New pods from HPA won't be in instance_map and may not function correctly
# - See docs/WORKER-SCALING-GUIDE.md for manual scaling procedures

---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: synapse-media-repository-pdb
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: media-repository
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
      app.kubernetes.io/component: media-repository
