---
# CloudNativePG Cluster for LI Instance
# Writable database synchronized from main via pg_dump/pg_restore
# Configured for lawful intercept with infinite message retention
# LI admin can modify data (e.g., reset passwords) - changes overwritten on next sync
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgresql-li
  namespace: matrix
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: matrix-stack
    matrix.instance: li
spec:
  # CLAUDE.md Section 3.4 & 7.1: LI does NOT require HA - single instance
  # LI is used by 1-2 admin users only, not production traffic
  instances: 1

  # Enable superuser access (creates matrix-postgresql-li-superuser secret)
  enableSuperuserAccess: true

  # Primary update strategy
  primaryUpdateStrategy: unsupervised

  # No sync replicas for single-instance LI
  # minSyncReplicas/maxSyncReplicas not needed with 1 instance

  # PostgreSQL version (must match main cluster)
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1

  # Storage configuration
  storage:
    size: 1Ti  # Larger than main due to infinite retention
    storageClass: standard

  # PostgreSQL configuration
  postgresql:
    parameters:
      # Connection settings
      # Increased from 200 to 500 to support read-heavy workload and monitoring
      # LI Synapse has fewer workers but forensic queries can be connection-intensive
      max_connections: "500"
      superuser_reserved_connections: "5"

      # Memory settings
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      work_mem: "64MB"  # Increased from 8MB for complex forensic queries

      # WAL settings
      wal_buffers: "16MB"
      min_wal_size: "1GB"
      max_wal_size: "2GB"
      wal_level: "replica"  # LI instance doesn't need logical replication
      max_wal_senders: "5"
      max_replication_slots: "5"

      # Checkpoint settings
      checkpoint_completion_target: "0.9"
      checkpoint_timeout: "15min"

      # Query planner
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      default_statistics_target: "100"

      # Logging
      log_destination: "csvlog"
      logging_collector: "on"
      log_directory: "log"
      log_filename: "postgresql-%Y-%m-%d.log"
      log_rotation_age: "1d"
      log_rotation_size: "100MB"
      log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"

      # Performance
      autovacuum_max_workers: "2"
      autovacuum_naptime: "1min"

      # Security
      ssl: "on"
      password_encryption: "scram-sha-256"

      # LI database is WRITABLE (not read-only)
      # LI admin needs to reset user passwords for lawful intercept
      # Changes in LI are overwritten by next sync (pg_dump/pg_restore)
      # default_transaction_read_only: "off" is the default, no need to set

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: matrix_li
      owner: synapse_li
      encoding: UTF8
      localeCollate: C
      localeCType: C
      # Note: Database populated via pg_dump/pg_restore from main
      # See deployment/li-instance/04-synapse-li-sync/ for sync CronJob

  # Monitoring configuration
  monitoring:
    enabled: true
    podMonitorEnabled: true

  # Resources (smaller than main)
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "8Gi"
      cpu: "2"

  # Backup configuration to MinIO
  backup:
    barmanObjectStore:
      destinationPath: s3://postgresql-backups/li/
      endpointURL: http://minio.matrix.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-credentials
          key: access-key
        secretAccessKey:
          name: minio-credentials
          key: secret-key
      wal:
        compression: gzip
        maxParallel: 2
    retentionPolicy: "90d"  # Longer retention for LI compliance

  # Affinity rules
  affinity:
    # CLAUDE.md Section 7.1: All LI services must run on one server
    # This ensures PostgreSQL LI runs on the designated LI node
    nodeSelector:
      node-role.kubernetes.io/li: "true"

    # Tolerate LI node taints (if the node is dedicated to LI workloads)
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "li"
        effect: "NoSchedule"

    # Note: podAntiAffinity is not needed for single-instance LI PostgreSQL
    # All LI services run on the same node by design (CLAUDE.md 7.1)
