---
# CloudNativePG Cluster for Main Matrix Instance
# Provides HA PostgreSQL with automatic failover
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-postgresql
  namespace: matrix
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: matrix-stack
    matrix.instance: main
spec:
  # High Availability Configuration
  instances: 3  # 1 primary + 2 replicas

  # Enable superuser access (creates matrix-postgresql-superuser secret)
  enableSuperuserAccess: true

  # Primary update strategy
  # unsupervised: automated switchover when replicas are ready
  primaryUpdateStrategy: unsupervised

  # Synchronous replication for data safety
  # Ensures at least 1 replica has received the data before commit
  minSyncReplicas: 1
  maxSyncReplicas: 2

  # PostgreSQL version
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1

  # Storage configuration
  storage:
    size: 500Gi
    storageClass: standard  # Adjust based on cloud provider

  # PostgreSQL configuration
  postgresql:
    parameters:
      # Connection settings
      max_connections: "500"
      superuser_reserved_connections: "3"

      # Memory settings (25% of RAM for shared_buffers, 75% for cache)
      shared_buffers: "4GB"     # 25% of 16GB
      effective_cache_size: "12GB"  # 75% of 16GB
      maintenance_work_mem: "1GB"
      work_mem: "10MB"

      # WAL settings
      wal_buffers: "16MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      wal_level: "logical"  # Required for LI instance logical replication
      max_wal_senders: "10"
      max_replication_slots: "10"

      # Checkpoint settings
      checkpoint_completion_target: "0.9"
      checkpoint_timeout: "15min"

      # Query planner
      random_page_cost: "1.1"  # For SSD storage
      effective_io_concurrency: "200"
      default_statistics_target: "100"

      # Logging
      log_destination: "csvlog"
      logging_collector: "on"
      log_directory: "log"
      log_filename: "postgresql-%Y-%m-%d.log"
      log_rotation_age: "1d"
      log_rotation_size: "100MB"
      log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
      log_temp_files: "0"
      log_autovacuum_min_duration: "0"
      log_error_verbosity: "default"

      # Performance
      autovacuum_max_workers: "3"
      autovacuum_naptime: "30s"

      # Security
      ssl: "on"
      password_encryption: "scram-sha-256"

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: matrix
      owner: synapse
      encoding: UTF8
      localeCollate: C
      localeCType: C
      postInitSQL:
        - CREATE DATABASE matrix_authentication_service OWNER synapse;
        - CREATE DATABASE key_vault OWNER synapse;

  # Monitoring configuration
  monitoring:
    enabled: true
    podMonitorEnabled: true

  # Resources (aligned with scaling guide for 100+ CCU)
  resources:
    requests:
      memory: "16Gi"  # Scaling guide: 16GB for 100 CCU
      cpu: "4"        # Scaling guide: 4 vCPU for 100 CCU
    limits:
      memory: "32Gi"  # Allow bursting for peak loads
      cpu: "8"        # Allow CPU bursting

  # Backup configuration to MinIO
  backup:
    barmanObjectStore:
      destinationPath: s3://postgresql-backups/main/
      endpointURL: http://minio.matrix.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-credentials
          key: access-key
        secretAccessKey:
          name: minio-credentials
          key: secret-key
      wal:
        compression: gzip
        maxParallel: 4
    retentionPolicy: "30d"

  # Affinity rules to spread across nodes
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                cnpg.io/cluster: matrix-postgresql
            topologyKey: kubernetes.io/hostname
