---
# Scheduled Backup for Main PostgreSQL Cluster
# Daily full backups at 2 AM
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: matrix-postgresql-daily-backup
  namespace: matrix
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: backup
    matrix.instance: main
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  backupOwnerReference: self
  cluster:
    name: matrix-postgresql
---
# Scheduled Backup for LI PostgreSQL Cluster
# Daily full backups at 3 AM (offset from main)
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: matrix-postgresql-li-daily-backup
  namespace: matrix
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: backup
    matrix.instance: li
spec:
  schedule: "0 3 * * *"  # Every day at 3 AM
  backupOwnerReference: self
  cluster:
    name: matrix-postgresql-li
