---
# MinIO Configuration Secret
# Contains root credentials and erasure coding configuration
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="CHANGE_ME_GENERATE_SECURE_PASSWORD"
    # Erasure Coding: EC:4 = 4 data shards + 4 parity shards
    # Requires minimum 8 drives (4 servers × 2 volumes each or 8 servers × 1 volume)
    # Can tolerate loss of 4 drives
    export MINIO_STORAGE_CLASS_STANDARD="EC:4"
    export MINIO_BROWSER="on"
    # Performance tuning
    export MINIO_API_REQUESTS_MAX="10000"
    export MINIO_API_REQUESTS_DEADLINE="10s"
---
# MinIO User Credentials Secret
# Used for application access (Synapse, PostgreSQL backup)
apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  # Base64 encoded credentials for application access
  # Generate with: echo -n "synapse" | base64
  CONSOLE_ACCESS_KEY: c3luYXBzZQ==  # "synapse"
  CONSOLE_SECRET_KEY: Q0hBTkdFX01FX0dFTkVSQVRFX1NFQ1VSRV9QQVNTV09SRA==  # CHANGE_ME
---
# MinIO Credentials for External Access
# Used by CloudNativePG and applications
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  access-key: "synapse"
  secret-key: "CHANGE_ME_GENERATE_SECURE_PASSWORD"
