---
# MinIO Configuration Secret
# Contains root credentials and erasure coding configuration
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: config
type: Opaque
stringData:
  config.env: |-
    # Root credentials (change these!)
    export MINIO_ROOT_USER="minio-root"
    export MINIO_ROOT_PASSWORD="CHANGE_ME_GENERATE_SECURE_PASSWORD_32_CHARS"

    # Erasure Coding Configuration
    # EC:4 means 4 data shards + 4 parity shards
    # With 8 total drives (4 servers × 2 volumes), we get 50% efficiency
    # Can tolerate up to 4 drive failures without data loss
    export MINIO_STORAGE_CLASS_STANDARD="EC:4"

    # Browser console
    export MINIO_BROWSER="on"

    # Prometheus metrics (public for scraping)
    export MINIO_PROMETHEUS_AUTH_TYPE="public"

    # Region (optional, for S3 compatibility)
    export MINIO_REGION="us-east-1"

    # Additional performance tuning
    export MINIO_API_REQUESTS_MAX="10000"
    export MINIO_API_REQUESTS_DEADLINE="10s"

---
# MinIO Application Credentials
# Used by MinIO Tenant, Synapse, and CloudNativePG for S3 access
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  # MinIO Tenant expects base64-encoded keys with these names
  CONSOLE_ACCESS_KEY: "synapse-s3-user"
  CONSOLE_SECRET_KEY: "CHANGE_ME_GENERATE_SECURE_S3_PASSWORD"

  # CloudNativePG and applications expect plain text with these names
  access-key: "synapse-s3-user"
  secret-key: "CHANGE_ME_GENERATE_SECURE_S3_PASSWORD"

---
# MinIO Service Alias
# The MinIO Operator creates services named "<tenant-name>-hl" (e.g., matrix-minio-hl)
# This ExternalName service provides a stable "minio" alias used by all applications
# Allows configs to use simple "minio.matrix.svc.cluster.local" endpoint
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: matrix
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: alias
spec:
  type: ExternalName
  externalName: matrix-minio-hl.matrix.svc.cluster.local
