# Synapse Secrets
# Contains sensitive configuration values
# WARNING: Replace all placeholder values before deploying to production!
#
# Generate secure random values using:
#   openssl rand -base64 32
#
# For signing key, use:
#   docker run -it --rm -v $(pwd):/data matrixdotorg/synapse:latest generate
#
# IMPORTANT: In production, use sealed-secrets, external-secrets, or vault

apiVersion: v1
kind: Secret
metadata:
  name: synapse-secrets
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: homeserver
    matrix.instance: main
type: Opaque
stringData:
  # Database credentials (must match PostgreSQL cluster)
  DB_PASSWORD: "CHANGEME_SECURE_DB_PASSWORD"

  # Redis password (must match Redis secret)
  REDIS_PASSWORD: "CHANGEME_SECURE_REDIS_PASSWORD"

  # S3/MinIO credentials (must match MinIO secret)
  S3_ACCESS_KEY: "synapse-s3-user"
  S3_SECRET_KEY: "CHANGEME_SECURE_S3_PASSWORD"

  # Worker replication secret (random 32-byte base64)
  REPLICATION_SECRET: "CHANGEME_SECURE_REPLICATION_SECRET"

  # Synapse core secrets (generate using: openssl rand -base64 32)
  MACAROON_SECRET: "CHANGEME_SECURE_MACAROON_SECRET"
  REGISTRATION_SECRET: "CHANGEME_SECURE_REGISTRATION_SECRET"
  FORM_SECRET: "CHANGEME_SECURE_FORM_SECRET"

  # TURN/coturn shared secret (must match coturn secret)
  TURN_SECRET: "CHANGEME_SECURE_TURN_SECRET"

  # key_vault API key (for E2EE recovery key storage)
  KEY_VAULT_API_KEY: "CHANGEME_SECURE_KEY_VAULT_API_KEY"

  # Synapse signing key (generate using synapse:latest generate command)
  # This is a multi-line key file
  signing.key: |
    ed25519 a_XXXX CHANGEME_GENERATE_USING_SYNAPSE_GENERATE_COMMAND
    # Replace this with actual signing key generated by Synapse
    # Use: docker run -it --rm -v $(pwd):/data matrixdotorg/synapse:latest generate
    # Then copy the content of the generated signing.key file

---
# Secret for database connection (used by initContainers and jobs)
apiVersion: v1
kind: Secret
metadata:
  name: synapse-db-credentials
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: database
    matrix.instance: main
type: Opaque
stringData:
  username: "synapse"
  password: "CHANGEME_SECURE_DB_PASSWORD"
  database: "matrix"
  host: "matrix-postgresql-rw.matrix.svc.cluster.local"
  port: "5432"

---
# Secret for S3/MinIO connection (used by media workers)
apiVersion: v1
kind: Secret
metadata:
  name: synapse-s3-credentials
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: media
    matrix.instance: main
type: Opaque
stringData:
  access-key: "synapse-s3-user"
  secret-key: "CHANGEME_SECURE_S3_PASSWORD"
  endpoint: "http://minio.matrix.svc.cluster.local:9000"
  bucket: "synapse-media"
