---
# Redis Password Secret
# Generate a secure random password before applying
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
type: Opaque
stringData:
  # IMPORTANT: Replace with a secure random password before deploying
  # Generate with: openssl rand -base64 32
  password: "CHANGE_ME_GENERATE_SECURE_PASSWORD"
