# Redis with Sentinel for High Availability
# NOTE: Redis Secret is defined separately in redis-secret.yaml
# Apply redis-secret.yaml BEFORE applying this file
# Provides automatic failover for Synapse and LiveKit
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
data:
  redis.conf: |
    # Network
    bind 0.0.0.0
    port 6379
    # protected-mode yes is the secure default. Password authentication is
    # configured via requirepass (added by init container from Secret).
    # Network isolation is enforced by Kubernetes NetworkPolicies.
    protected-mode yes

    # General
    daemonize no
    supervised no
    loglevel notice

    # Persistence - AOF for durability
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Disable RDB (using AOF instead)
    save ""

    # Replication
    replica-read-only yes
    repl-diskless-sync yes
    repl-diskless-sync-delay 5

    # Memory management
    # Increased from 2gb to 8gb for high-scale deployments (5K-20K CCU)
    # At 20K CCU: ~500MB LiveKit sessions + ~100MB presence + ~200MB ratelimits + ~100MB worker locks = ~1GB baseline
    # 8GB provides ample headroom for cache and prevents eviction of critical data
    maxmemory 8gb
    # Changed from allkeys-lru to volatile-lru to prevent eviction of worker coordination locks
    # Only keys with TTL (cache data) will be evicted, persistent keys (locks, sessions) retained
    maxmemory-policy volatile-lru

    # Security
    # Password will be set via command line argument from Secret
    # requirepass and masterauth configured at runtime

    # Performance
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: sentinel
data:
  sentinel.conf: |
    bind 0.0.0.0
    port 26379

    # Monitor the master
    sentinel monitor mymaster redis-0.redis-headless.matrix.svc.cluster.local 6379 2
    # Password will be set at runtime from Secret

    # Timing configuration
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1

    # Logging
    loglevel notice
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: sentinel
      port: 26379
      targetPort: sentinel
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: sentinel
      port: 26379
      targetPort: sentinel
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: matrix
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: matrix-stack
    matrix.instance: main
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: database
        matrix.instance: main
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis
                topologyKey: kubernetes.io/hostname

      initContainers:
        # Initialize Redis configuration with password
        - name: init-redis
          image: redis:7.2-alpine
          command:
            - sh
            - -c
            - |
              set -e
              cp /mnt/config/redis.conf /data/redis.conf
              echo "" >> /data/redis.conf
              echo "# Password from Secret" >> /data/redis.conf
              echo "requirepass ${REDIS_PASSWORD}" >> /data/redis.conf
              echo "masterauth ${REDIS_PASSWORD}" >> /data/redis.conf
              chmod 644 /data/redis.conf
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

        # Initialize Sentinel configuration
        - name: init-sentinel
          image: redis:7.2-alpine
          command:
            - sh
            - -c
            - |
              set -e
              cp /mnt/config/sentinel.conf /data/sentinel.conf
              echo "" >> /data/sentinel.conf
              echo "# Password from Secret" >> /data/sentinel.conf
              echo "sentinel auth-pass mymaster ${REDIS_PASSWORD}" >> /data/sentinel.conf
              chmod 644 /data/sentinel.conf
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          volumeMounts:
            - name: sentinel-config
              mountPath: /mnt/config
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

        # Initialize Redis master-replica replication
        - name: init-replication
          image: redis:7.2-alpine
          command:
            - sh
            - -c
            - |
              set -e
              # Get hostname to determine if this is a replica
              HOSTNAME=$(hostname)
              echo "Initializing Redis replication for: ${HOSTNAME}"

              # Append replication config if this is not redis-0
              if [ "${HOSTNAME}" != "redis-0" ]; then
                echo "" >> /data/redis.conf
                echo "# Replica configuration" >> /data/redis.conf
                echo "replicaof redis-0.redis-headless.matrix.svc.cluster.local 6379" >> /data/redis.conf
                echo "masterauth ${REDIS_PASSWORD}" >> /data/redis.conf
                echo "Configured ${HOSTNAME} as replica of redis-0"
              else
                echo "Configured ${HOSTNAME} as master"
              fi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"

      containers:
        # Redis container
        - name: redis
          image: redis:7.2-alpine
          command:
            - redis-server
            - /data/redis.conf
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              # IMPORTANT: Request MUST match or exceed maxmemory (8gb) to ensure
              # Kubernetes schedules the pod on a node with sufficient memory
              memory: "8Gi"  # Must match maxmemory in redis.conf
              cpu: "500m"    # Increased for high-throughput operations
            limits:
              memory: "10Gi"  # Buffer above maxmemory for Redis overhead
              cpu: "2"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data

        # Sentinel container
        - name: sentinel
          image: redis:7.2-alpine
          command:
            - redis-sentinel
            - /data/sentinel.conf
          ports:
            - name: sentinel
              containerPort: 26379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -p 26379 ping | grep PONG
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -p 26379 ping | grep PONG
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: sentinel-config
          configMap:
            name: redis-sentinel-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: matrix
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
