---
# Cert-Manager Installation
# Automatic TLS certificate management
# DO NOT apply this file directly - follow the instructions below

# Installation Method: Using kubectl
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml

# Verification:
# kubectl get pods -n cert-manager

---
# ClusterIssuer for Let's Encrypt Production
# Used for automatic TLS certificate generation
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for expiration notifications
    email: admin@example.com  # CHANGE THIS

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-private-key

    # HTTP-01 challenge
    solvers:
      - http01:
          ingress:
            class: nginx
---
# ClusterIssuer for Let's Encrypt Staging (Testing)
# Use this for testing before switching to production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (higher rate limits)
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    email: admin@example.com  # CHANGE THIS

    privateKeySecretRef:
      name: letsencrypt-staging-private-key

    solvers:
      - http01:
          ingress:
            class: nginx
---
# ClusterIssuer for Self-Signed Certificates (Air-Gapped)
# Use this for air-gapped deployments or internal testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# Example Certificate for Testing
# Tests cert-manager is working correctly
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: matrix
spec:
  secretName: test-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: test.example.com
  dnsNames:
    - test.example.com
